// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhwnmt-8StbxK0wETUjLKqzr3Tkqv3zT8',
    appId: '1:798992647445:web:449ac2bf494694ddeb551c',
    messagingSenderId: '798992647445',
    projectId: 'generate-live-caption-ce788',
    authDomain: 'generate-live-caption-ce788.firebaseapp.com',
    storageBucket: 'generate-live-caption-ce788.appspot.com',
    measurementId: 'G-5QJXH8NYM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwxxRp620hoC9msz4JlZGqHyZiuqDTSQM',
    appId: '1:798992647445:android:09827c8ae0a4c654eb551c',
    messagingSenderId: '798992647445',
    projectId: 'generate-live-caption-ce788',
    storageBucket: 'generate-live-caption-ce788.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYfgCgPx3YjB_sk3Oi3wnXfc1w_5APQ4c',
    appId: '1:798992647445:ios:80708d46c154e700eb551c',
    messagingSenderId: '798992647445',
    projectId: 'generate-live-caption-ce788',
    storageBucket: 'generate-live-caption-ce788.appspot.com',
    iosBundleId: 'com.example.generatelivecaption',
  );
}
